apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "spring-cubix-hw5.fullname" . }}
  labels:
    {{- include "spring-cubix-hw5.labels" . | nindent 4 }}
spec:
  podMetricsEndpoints:
    - port: management
      path: /actuator/prometheus
  selector:
    matchLabels:
      {{- include "spring-cubix-hw5.selectorLabels" . | nindent 6 }}
